[build]
  publish = "build"
  functions = "netlify/functions"
  command = "bash build.sh"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = "netlify/functions"
